/**
 * Regenerates public/vendor/remixicon-subset.css from the installed remixicon package.
 *
 * The page loaded the full 120 KB stylesheet from jsdelivr, which is frequently unreachable
 * for the mainland-China audience this panel targets — and when it failed, all ~90 icons
 * silently disappeared. This ships only the glyphs actually used (about 2 KB of CSS) plus the
 * woff2, so the icon layer has no third-party dependency.
 *
 * Run after adding an icon to the page:  node scripts/build-icons.mjs
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = join(root, 'public');
const vendorDir = join(publicDir, 'vendor');

/** Every `ri-*` class referenced by the page, discovered rather than hand-maintained. */
function usedIcons() {
  const sources = readdirSync(publicDir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && /\.(html|js|css)$/.test(entry.name))
    .map((entry) => readFileSync(join(publicDir, entry.name), 'utf8'))
    .join('\n');
  return [...new Set(sources.match(/ri-[a-z0-9-]+/g) ?? [])].sort();
}

const icons = usedIcons();
if (!icons.length) {
  throw new Error('no ri-* classes found under public/ — refusing to write an empty subset');
}

const css = readFileSync(join(root, 'node_modules/remixicon/fonts/remixicon.css'), 'utf8');
const rules = [];
const missing = [];

for (const name of icons) {
  const match = css.match(new RegExp(`\\.${name}:before\\s*\\{\\s*content:\\s*"([^"]+)";?\\s*\\}`));
  if (match) {
    rules.push(`.${name}:before { content: "${match[1]}"; }`);
  } else {
    missing.push(name);
  }
}

if (missing.length) {
  throw new Error(`icons not present in remixicon: ${missing.join(', ')}`);
}

mkdirSync(vendorDir, { recursive: true });
copyFileSync(join(root, 'node_modules/remixicon/fonts/remixicon.woff2'), join(vendorDir, 'remixicon.woff2'));

writeFileSync(
  join(vendorDir, 'remixicon-subset.css'),
  `/*
 * Remixicon 3.5.0 (Apache-2.0) — subset containing only the ${rules.length} glyphs this page uses.
 * Generated by scripts/build-icons.mjs; do not edit by hand.
 */
@font-face {
  font-family: "remixicon";
  src: url("./remixicon.woff2") format("woff2");
  font-display: swap;
  font-weight: normal;
  font-style: normal;
}

[class^="ri-"],
[class*=" ri-"] {
  font-family: "remixicon" !important;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

${rules.join('\n')}
`,
  'utf8'
);

console.log(`build-icons: wrote ${rules.length} glyph rules + remixicon.woff2`);
